// <auto-generated />
namespace LibrarySystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class onetomanyrelationbetweenLoantransactionandBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onetomanyrelationbetweenLoantransactionandBook));
        
        string IMigrationMetadata.Id
        {
            get { return "202505140619168_one to many relation between Loantransaction and Book"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
