// <auto-generated />
namespace LibrarySystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtables));
        
        string IMigrationMetadata.Id
        {
            get { return "202505120837530_add tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
